import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function HomePage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary text-primary-foreground font-semibold text-sm">
              AWS
            </div>
            <span className="text-lg font-semibold">AWS Exam Prep</span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/auth/login">
              <Button variant="ghost">Sign in</Button>
            </Link>
            <Link href="/auth/signup">
              <Button>Get Started</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <main className="container mx-auto px-4 py-20">
        <div className="max-w-3xl mx-auto text-center space-y-8">
          <h1 className="text-5xl font-bold tracking-tight">
            Pass Your AWS Developer Associate Exam with{" "}
            <span className="text-primary">AI-Powered Practice</span>
          </h1>
          
          <p className="text-xl text-muted-foreground">
            Unlimited practice questions generated by AI, instant detailed feedback, 
            and progress tracking by service. Never see the same question twice.
          </p>

          <div className="flex justify-center gap-4">
            <Link href="/auth/signup">
              <Button size="lg" className="text-lg px-8">
                Start Free
              </Button>
            </Link>
            <Link href="#features">
              <Button size="lg" variant="outline" className="text-lg px-8">
                Learn More
              </Button>
            </Link>
          </div>

          <p className="text-sm text-muted-foreground">
            5 free questions per day • No credit card required
          </p>
        </div>

        {/* Features Section */}
        <section id="features" className="mt-32 max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">
            Everything you need to pass
          </h2>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="space-y-3 text-center">
              <div className="text-4xl">🎯</div>
              <h3 className="text-xl font-semibold">Service-by-Service</h3>
              <p className="text-muted-foreground">
                Practice Lambda, S3, DynamoDB, and 12 more AWS services covered on the DVA-C02 exam.
              </p>
            </div>
            
            <div className="space-y-3 text-center">
              <div className="text-4xl">🤖</div>
              <h3 className="text-xl font-semibold">AI-Generated Questions</h3>
              <p className="text-muted-foreground">
                Fresh, unique questions every time. Our AI creates exam-style scenarios you've never seen.
              </p>
            </div>
            
            <div className="space-y-3 text-center">
              <div className="text-4xl">💡</div>
              <h3 className="text-xl font-semibold">Learn Why</h3>
              <p className="text-muted-foreground">
                Detailed explanations for every answer—right and wrong—plus exam tips to remember concepts.
              </p>
            </div>
            
            <div className="space-y-3 text-center">
              <div className="text-4xl">📊</div>
              <h3 className="text-xl font-semibold">Track Progress</h3>
              <p className="text-muted-foreground">
                See your readiness score, identify weak areas, and know when you're ready to schedule the exam.
              </p>
            </div>
            
            <div className="space-y-3 text-center">
              <div className="text-4xl">🔄</div>
              <h3 className="text-xl font-semibold">No Repeats</h3>
              <p className="text-muted-foreground">
                We track every question you've seen. You'll never memorize answers—you'll learn concepts.
              </p>
            </div>
            
            <div className="space-y-3 text-center">
              <div className="text-4xl">⚡</div>
              <h3 className="text-xl font-semibold">Instant Feedback</h3>
              <p className="text-muted-foreground">
                No waiting. Get detailed AI feedback the moment you submit your answer.
              </p>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="mt-32 max-w-2xl mx-auto text-center space-y-6">
          <h2 className="text-3xl font-bold">
            Ready to pass your AWS exam?
          </h2>
          <p className="text-muted-foreground">
            Join developers who are studying smarter with AI-powered practice.
          </p>
          <Link href="/auth/signup">
            <Button size="lg" className="text-lg px-8">
              Get Started Free
            </Button>
          </Link>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-border mt-32">
        <div className="container mx-auto px-4 py-8 text-center text-sm text-muted-foreground">
          <p>© 2024 AWS Exam Prep. Not affiliated with Amazon Web Services.</p>
        </div>
      </footer>
    </div>
  )
}
